### ISSUE TITLE
"none" dates crash the compiler

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#53] opened 2020-04-08 16:44 UTC
When choosing from datetime option fiields in DURC if you choose "none" in phpyadmin it zeros out the date field. 

When DURC creates the syntax for this default it includes single quotes inside the single quotes for the php variable and breaks the php syntax. So its like: 

 $var_date = ''00:00:00 etc etc'';
where it should generate 
 $var_date = '00:00:00 etc etc';

This crashes compilation of DURC:write and is a show stopping bug

**Comment by kchapple** [comment] 2020-04-09 14:44
@ftrotter What PHP file (model, controller, function, etc.) was the malformed PHP generated in? I'm not able to reproduce this error using the following schema, where datetime_none and date_none columns use phpmyadmin's "none" option as default like this:
<img width="651" alt="Screen Shot 2020-04-09 at 10 42 15 AM" src="https://user-images.githubusercontent.com/271809/78907607-ec606700-7a4e-11ea-82ea-b00ca72630e5.png">

Here's the schema that was generated:

CREATE TABLE `test_default_date` (
  `id` int(11) NOT NULL,
  `datetime_none` datetime NOT NULL,
  `date_none` date NOT NULL,
  `datetime_current` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_current` varchar(255) DEFAULT 'Current timestamp not supported for date',
  `datetime_null` datetime DEFAULT NULL,
  `date_null` date DEFAULT NULL,
  `datetime_defined` datetime NOT NULL DEFAULT '2000-01-01 01:23:45',
  `date_defined` date NOT NULL DEFAULT '2000-01-01'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `test_default_dates`
  ADD PRIMARY KEY (`id`);

**Comment by kchapple** [comment] 2020-04-09 14:45
I did find other errors related to dates and defaults that I am looking at.

**Comment by kchapple** [comment] 2020-05-01 20:48
@seanccsmith I think I may have found and fixed this, as I came across it in my testing another issue today, but haven't tested Fred's specific case though.

**Comment by seanccsmith** [comment] 2020-05-06 22:07
This problem should be seen when running durc:write, correct? And not when adding new data or anything else?

I've switched some data fields in the db schemas from NULL to None, and am able to run durc:write with no problems. If those are the steps to replicate, this issue can be closed.

**Comment by seanccsmith** [comment] 2020-05-07 16:44
Confirmed, the compiler no longer crashes when date fields are None by default. Closing issue.

**Closed as completed by seanccsmith** 2020-05-07 16:44 UTC
Labels: 1.0 requirement, Ready for QA
